### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by UneebKari** [Chaser324/soundcloud-unity#1]
Hey dev

did you still not finish that project, 
Any update?

**Comment by Chaser324** [comment]
I haven't really pursued this further due to concerns about the API rate limit and transcoding. That said, the basic functionality here totally does work - just tested in Unity 5.6.1. All you have to do is just fill in an API key in SCConfig.CLIENT_ID and drop an ffmpeg executable into a SoundCloud-Unity/FFMPEG directory (or change the ffmpeg file path being used in SCTranscoder).
